classdef saturation_plugin < audioPlugin
% reverb plugin object

  properties
    bypass = 'Off'
    mix = 1
    type = 'cubic'
    in_gain = 1
    dist_gain = 1
  end
  
  properties (Constant, Hidden)
    PluginInterface = audioPluginInterface( ...
    audioPluginParameter( ...
        'bypass','Mapping',{'enum', 'On', 'Off'}, ...
        'DisplayName', 'Enable', ...
        'Layout',[1,1]), ...
    audioPluginParameter( ...
        'mix','Mapping',{'lin', 0, 1}, ...
        'Style','rotary', ...
        'Layout',[1,2]), ...
    audioPluginParameter('type', ...
        'Mapping',{'enum', 'cubic', 'arctan', 'tanh'}, ...
        'Layout',[1,3]), ...
    audioPluginParameter( ...
        'in_gain','Mapping',{'pow', 1/3, -10, 6}, ...
        'DisplayName', 'Input Gain (dB)', ...
        'Style','rotary', ...
        'Layout',[3,1]), ...
    audioPluginParameter( ...
        'dist_gain','Mapping',{'pow', 1/3, -10, 6}, ...
        'DisplayName', 'Distortion Gain (dB)', ...
        'Style','rotary', ...
        'Layout',[3,2]), ...
    'PluginName', 'Saturation Effect', ...
    audioPluginGridLayout( ...
        'RowHeight',[100,100,150,80,80], ...
        'ColumnWidth',[125,125,100,100], ...
        'RowSpacing',10));

  end
  
  methods    
    function out = process(plugin, in)
        dry = in; %use input to get wet/dry data for mixing
        wet = in; 

        if(strcmp(plugin.bypass,'Off'))
            out = dry;
            return
        end
        
        %apply effects to wet data
        switch plugin.type
        case "cubic"
            %Cubic distortion
            wet(:,1) = plugin.in_gain*in(:,1) - plugin.dist_gain*(1/3)*in(:,1).^3;
            wet(:,2) = plugin.in_gain*in(:,2) - plugin.dist_gain*(1/3)*in(:,2).^3;
        case "arctan"
            %arctan distortion
            wet(:,1) = (2/pi)*atan(in(:,1).*plugin.dist_gain*plugin.in_gain); 
            wet(:,2) = (2/pi)*atan(in(:,2).*plugin.dist_gain*plugin.in_gain);
        case "tanh"
            %tanh distortion
            wet(:,1) = tanh(in(:,1).*plugin.dist_gain*plugin.in_gain); 
            wet(:,2) = tanh(in(:,2).*plugin.dist_gain*plugin.in_gain);
            otherwise
            %Default to cubic distortion
            wet(:,1) = plugin.in_gain*in(:,1) - plugin.dist_gain*(1/3)*in(:,1).^3;
            wet(:,2) = plugin.in_gain*in(:,2) - plugin.dist_gain*(1/3)*in(:,2).^3;
        end
        %Mix data into output
        out = (1-plugin.mix)*dry + (plugin.mix)*wet;
        %out(:,1) = (1-plugin.mix)*dry(:,1) + (plugin.mix)*wet(:,1);
        %out(:,2) = (1-plugin.mix)*dry(:,2) + (plugin.mix)*wet(:,2);
    end
  end
end